
local items = {
    -- bobores
    ["tin-ore"] = 1,
    ["lead-ore"] = 1,
    ["quartz"] = 1,
    ["bauxite-ore"] = 2,
    ["cobalt-ore"] = 2,
    ["nickel-ore"] = 2,
    ["rutile-ore"] = 2,
    ["thorium-ore"] = 2,
    ["silver-ore"] = 2,
    ["tungsten-ore"] = 2,
    ["zinc-ore"] = 2,
    ["gold-ore"] = 2,
    ["gem-ore"] = 2,
    ["ruby-ore"] = 2,
    ["sapphire-ore"] = 2,
    ["emerald-ore"] = 2,
    ["amethyst-ore"] = 2,
    ["topaz-ore"] = 2,
    ["diamond-ore"] = 2,

    -- bobelectronics
    -- electronics
    ["tinned-copper-cable"] = 1,
    ["insulated-cable"] = 1,
    ["gilded-copper-cable"] = 2,
    ["solder"] = 1,
    ["basic-electronic-components"] = 1,
    ["electronic-components"] = 1,
    ["intergrated-electronics"] = 2,
    ["processing-electronics"] = 3,
    ["wooden-board"] = 1,
    ["phenolic-board"] = 2,
    ["fibreglass-board"] = 3,
    ["basic-circuit-board"] = 1,
    ["circuit-board"] = 1,
    ["superior-circuit-board"] = 2,
    ["multi-layer-circuit-board"] = 3,
    ["electronic-circuit"] = 1,
    ["advanced-circuit"] = 1,
    ["processing-unit"] = 2,
    ["advanced-processing-unit"] = 3,
    -- resource
    ["resin"] = 1,
    ["rubber"] = 1,
    ["silicon-wafer"] = 1,
    ["solder-alloy"] = 1,

    -- bobplates
    -- alien
    ["alien-blue-alloy"] = 2,
    ["alien-orange-alloy"] = 2,
    -- alloys
    ["bronze-alloy"] = 1,
    ["brass-alloy"] = 1,
    ["copper-tungsten-alloy"] = 2,
    ["tungsten-carbide"] = 2,
    ["gunmetal-alloy"] = 1,
    ["invar-alloy"] = 2,
    ["nitinol-alloy"] = 2,
    ["cobalt-steel-alloy"] = 2,
    -- chemicals
    ["salt"] = 1,
    ["lithium-chloride"] = 2,
    ["lithium-perchlorate"] = 2,
    ["sodium-hydroxide"] = 1,
    ["calcium-chloride"] = 1,
    ["lead-oxide"] = 1,
    ["alumina"] = 1,
    ["tungsten-oxide"] = 2,
    ["powdered-tungsten"] = 2,
    ["silicon-powder"] = 1,
    ["silicon-nitride"] = 1,
    ["cobalt-oxide"] = 2,
    ["silicon-carbide"] = 1,
    ["silver-nitrate"] = 2,
    ["silver-oxide"] = 2,
    -- gems
    ["ruby-3"] = 1,
    ["ruby-4"] = 1,
    ["ruby-5"] = 1,
    ["sapphire-3"] = 1,
    ["sapphire-4"] = 1,
    ["sapphire-5"] = 1,
    ["emerald-3"] = 1,
    ["emerald-4"] = 1,
    ["emerald-5"] = 1,
    ["amethyst-3"] = 1,
    ["amethyst-4"] = 1,
    ["amethyst-5"] = 1,
    ["topaz-3"] = 1,
    ["topaz-4"] = 1,
    ["topaz-5"] = 1,
    ["diamond-3"] = 1,
    ["diamond-4"] = 1,
    ["diamond-5"] = 1,
    -- parts
    ["steel-gear-wheel"] = 1,
    ["steel-bearing-ball"] = 1,
    ["steel-bearing"] = 1,
    ["brass-gear-wheel"] = 1,
    ["cobalt-steel-gear-wheel"] = 2,
    ["cobalt-steel-bearing-ball"] = 2,
    ["cobalt-steel-bearing"] = 2,
    ["titanium-gear-wheel"] = 2,
    ["titanium-bearing-ball"] = 2,
    ["titanium-bearing"] = 2,
    ["tungsten-gear-wheel"] = 2,
    ["nitinol-gear-wheel"] = 2,
    ["nitinol-bearing-ball"] = 2,
    ["nitinol-bearing"] = 2,
    ["ceramic-bearing-ball"] = 2,
    ["ceramic-bearing"] = 2,
    ["lithium-ion-battery"] = 3,
    ["silver-zinc-battery"] = 3,
    -- plates
    ["tin-plate"] = 1,
    ["silver-plate"] = 1,
    ["lead-plate"] = 1,
    ["gold-plate"] = 1,
    ["nickel-plate"] = 1,
    ["zinc-plate"] = 1,
    ["aluminium-plate"] = 1,
    ["titanium-plate"] = 2,
    ["tungsten-plate"] = 2,
    ["silicon"] = 1,
    ["lithium"] = 1,
    ["cobalt-plate"] = 2,
    -- resource
    ["carbon"] = 1,
    -- resin
    -- rubber
    ["glass"] = 1,
    -- silicon-wafer
    ["lithium-cobalt-oxide"] = 2,
    ["enriched-fuel"] = 2,

    -- bobmodules
    -- electronics
    -- ["module-case"] = 1,
    ["module-contact"] = 1,
    -- ["module-circuit-board"] = 1,
    ["module-processor-board"] = 1,
    ["module-processor-board-2"] = 2,
    ["module-processor-board-3"] = 3,
    ["speed-processor"] = 1,
    ["speed-processor-2"] = 2,
    ["speed-processor-3"] = 3,
    ["effectivity-processor"] = 1,
    ["effectivity-processor-2"] = 2,
    ["effectivity-processor-3"] = 3,
    ["productivity-processor"] = 1,
    ["productivity-processor-2"] = 2,
    ["productivity-processor-3"] = 3,
    ["pollution-clean-processor"] = 1,
    ["pollution-clean-processor-2"] = 2,
    ["pollution-clean-processor-3"] = 3,
    ["pollution-create-processor"] = 1,
    ["pollution-create-processor-2"] = 2,
    ["pollution-create-processor-3"] = 3,

}

for item, level in pairs(items) do
    deadlock_crating.create(item, "deadlock-crating-"..level)
end

